[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
marketplace = "Fi1J1rh4vTfiqWDLyfjW18r3teyfeTWwdLWf8JUNyf9x"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
